version: '2'

services:
  ci-build:
    image: <%= sdk_image %>
    container_name: build
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "dotnet restore ./<%= project_name %>.csproj && dotnet publish ./<%= project_name %>.csproj -c Release -o ./build"