version: '2'

services:
  <%= service_name %>:
    image: <%= image_name %>
    build:
      context: .
      dockerfile: Dockerfile
      args:
        source: ./build
    ports:
      - "<%= port_number %>:<%= port_number %>"
